- alias: "GSR1"
  stream_type: "GSR"
  stream_name: "Shimmer_GSR_FBF5_26"
  stream_source_id: ""
  filter_params:
    low_cut: null
    high_cut: 8
    sfreq: 250
    filter_order: 2
    notch_filter: 50
    notch_filter_width: 5
    notch_filter_order: 2

- alias: "GSR2"
  stream_type: "GSR"
  stream_name: ""
  stream_source_id: "6c7cba554f14992e"
  filter_params:
    low_cut: null
    high_cut: 10
    sfreq: 250
    filter_order: 2
    notch_filter: 60
    notch_filter_width: 5
    notch_filter_order: 2
